icons_format = " {icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "material-nf"

[[block]]
block = "net"
device = "wlp9s0"
format = " $ssid $signal_strength"
interval = 3
click = [
    { button = "left", cmd = "nm-connection-editor" }
]

[[block]]
block = "bluetooth"
format = "{icon} $name"
interval = 5
click = [
    { button = "left", cmd = "overskride" }
]

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = " $available"
interval = 20

[[block]]
block = "memory"
format = " $mem_used_percents"
interval = 5

[[block]]
block = "cpu"
interval = 1
format = " $utilization"

[[block]]
block = "sound"
format = " $volume"
click = [
    { button = "left", cmd = "pavucontrol" }
]

[[block]]
block = "time"
format = " %a %d/%m %R"
