name: Perseus CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: DeterminateSystems/nix-installer-action@main
      
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Check flake
        run: |
          nix flake check
          nix flake show

      - name: Lint flake
        run: |
            nix run nixpkgs#statix -- check .
            nix run nixpkgs#deadnix --  .
      
      - name: Evaluate configurations
        run: |
          ./perseus.sh <<< $'testuser\ntesthost\nTest User\ntest@example.com\nfalse\nfalse\ny\ny\ny\n3\nn'
          git add user-config.nix
          git commit -m "temp config for CI"
          nix eval .#nixosConfigurations.testhost.config.system.build.toplevel

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - uses: DeterminateSystems/nix-installer-action@main
      
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: "NeoMedSys/perseus"
          tag: ${{ github.ref_name }}
          visibility: "public"
          token: ${{ secrets.FH_TOKEN }}
