name: Perseus CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: DeterminateSystems/nix-installer-action@main
      
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Check flake
        run: |
          nix flake check
          nix flake show

      - name: Lint flake
        run: |
            nix run nixpkgs#statix -- check .
            nix run nixpkgs#deadnix --  .
      
      - name: Evaluate configurations
        run: |
            nix eval .#nixosConfigurations.perseus.config.system.build.toplevel
            nix eval .#nixosConfigurations.perseus-gpu.config.system.build.toplevel

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: DeterminateSystems/nix-installer-action@main
      
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: "NeoMedSys/perseus"
          tag: "v0.1.0"
          visibility: "private"
          token: ${{ secrets.FH_TOKEN }}
