name: Perseus CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - name: Check flake
        run: |
          nix flake check
          nix flake show

      - name: Lint flake
        run: |
          nix run nixpkgs#statix -- check .
          nix run nixpkgs#deadnix .

      - name: Evaluate configurations
        run: |
          echo "=== user-config.nix ==="
          cat user-config.nix
          echo "=== Evaluate build ==="
          nix eval .#nixosConfigurations.perseus.config.system.build.toplevel

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/flakehub-push@v5
        with:
          name: "NeoMedSys/perseus"
          tag: ${{ github.ref_name }}
          visibility: public
          token: ${{ secrets.FH_TOKEN }}