name: Perseus CI CD
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - run: nix flake check
      - run: nix flake show
      - run: nix run nixpkgs#statix -- check .
      - run: nix run nixpkgs#deadnix -- .
      - run: nix eval .#nixosConfigurations.perseus.config.system.build.toplevel
  publish:
    if: github.event_name == push && github.ref == refs/heads/main
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: NeoMedSys/perseus
          tag: main
          visibility: public
          flakehub-push-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}