name: TruffleHog Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog and Check Output
        run: |
          # Run trufflehog and redirect output to a JSON file
          trufflehog --json . > trufflehog_report.json
          
          # Check if the file was created and has content
          if [ -s trufflehog_report.json ]; then
            echo "TruffleHog found secrets, outputting report:"
            cat trufflehog_report.json
          else
            echo "TruffleHog did not find any secrets. The report file is empty."
          fi

      - name: Upload TruffleHog Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog_report.json

